train : ./AllDataFiveClass(WithoutT22L600)/images/train/
val : ./AllDataFiveClass(WithoutT22L600)/images/val/


nc : 5

names : ["complete", "incomplete","blurry.complete","blurry.incomplete" , "hair"]